### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by dmahajan980** [dmahajan980/covid19#2]
The current README is a brief description of what the command-line tool does. It needs to be updated with a bit more details so that the users are aware of what the tool does. Apart from that, a GIF should also be added, which demonstrates how the CLI works and how results are displayed.

**Comment by ruddha2001** [comment]
Hello @dmahajan980 
I would like to take this issue up.

**Comment by dmahajan980** [comment]
Sure @ruddha2001!

Go ahead. Let me know if you have any questions :)
